subquery/subquid tutorial
kodadot/docs pull request #58
Opened 2022-06-03 18:01 UTC by thea-exe

I'll probably add 1-2 more examples but I went into depth with the first one, would like to see if it looks satisfactory first! I wrote this with first-time devs in mind.

2022-06-21 15:04 UTC, yangwao commented
@vikiival 👀

2022-06-21 16:58 UTC, thea-exe commented
@vikiival oh wait I think I was just showing that to explain stuff 😅

2022-06-21 16:59 UTC, thea-exe commented
It doesn't actually query anything, I wrote what it does :P

2022-06-22 10:58 UTC, vikiival requested changes
minor

2022-06-22 10:58 UTC, vikiival commented on docs/tutorials/querytutorial.md
> +KodaDot currently uses two types of indexers, [Subquery] and [SubSquid]. You can use this tutorial as a way to write queries for both indexers, however there are minimal differences that you should k
missing links for subquery and subsquid

2022-06-22 10:58 UTC, vikiival commented on docs/tutorials/querytutorial.md
> +The parameters are what helps the query find what you need. If one of your parameters is 'id', then the query will look for id's.
```suggestion
The parameters are what helps the query find what you need. If one of your parameters is `id`, then the query will look for id's.
```

2022-06-22 10:58 UTC, vikiival commented on docs/tutorials/querytutorial.md
> +Let's go through examples to show you how this works. If you'd like to understand how [general querying]() works, we have an article for that as well. In the meantime, these will be queries specific
possibly empty link?

2022-07-11 13:56 UTC, merged